import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {launchBrowser,siteUrl} from './runtime.mjs';
const browser=await launchBrowser();
await fs.mkdir('output/playwright',{recursive:true});
try {
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  const page=await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(siteUrl+'?tour=1');
  const dialog=page.getByRole('dialog',{name:'Найдите нужную лекцию'});
  await dialog.waitFor();
  assert.equal(await page.locator('#root').evaluate(el=>el.inert),true);
  await page.screenshot({path:'output/playwright/tour-catalog.png'});
  for(let i=0;i<4;i++)await page.getByRole('button',{name:'Далее',exact:true}).click();
  await page.getByRole('button',{name:'Открыть лекцию и продолжить'}).click();
  await page.getByRole('dialog',{name:'Перелистывайте слайды'}).waitFor();
  for(let i=0;i<4;i++)await page.getByRole('button',{name:'Далее',exact:true}).click();
  const popup=context.waitForEvent('page');
  await page.getByRole('button',{name:'Запустить два окна и продолжить'}).click();
  const audience=await popup;
  await page.getByRole('dialog',{name:'Подключите окно аудитории'}).waitFor();
  await audience.locator('[data-slide-id]').waitFor();
  assert.equal(await audience.locator('.guided-tour').count(),0);
  await page.getByRole('button',{name:'Далее',exact:true}).click();
  await page.waitForFunction(() => {
    const target=document.querySelector('[aria-label="Разделы заметок"]').getBoundingClientRect();
    const spot=document.querySelector('.tour-spotlight').getBoundingClientRect();
    const card=document.querySelector('.tour-card').getBoundingClientRect();
    return Math.abs(target.left-spot.left-5)<2 && card.bottom<=innerHeight;
  });
  await page.screenshot({path:'output/playwright/tour-notes.png'});
  for(let i=0;i<5;i++)await page.getByRole('button',{name:'Далее',exact:true}).click();
  await page.getByRole('button',{name:'Готово',exact:true}).click();
  assert.equal(await page.locator('#root').evaluate(el=>el.inert),false);
  await page.getByRole('button',{name:'Тур по кнопкам',exact:false}).click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.tour-card').count(),0);
  await audience.close();
  await page.setViewportSize({width:390,height:844});
  await page.goto(siteUrl+'?tour=1');
  await page.getByRole('dialog',{name:'Найдите нужную лекцию'}).waitFor();
  await page.waitForTimeout(300);
  await page.screenshot({path:'output/playwright/tour-mobile.png'});
  const geometry=await page.locator('.tour-card').boundingBox();
  assert.ok(geometry.x>=0 && geometry.x+geometry.width<=391);
  assert.ok(geometry.y>=0 && geometry.y+geometry.height<=845);
  await page.keyboard.press('Escape');
  await page.getByRole('textbox',{name:'Поиск по всему курсу'}).fill('несуществующаялекция000');
  await page.getByRole('button',{name:'Тур по кнопкам',exact:false}).click();
  for(let i=0;i<4;i++)await page.getByRole('button',{name:'Далее',exact:true}).click();
  await page.waitForTimeout(250);
  assert.equal(await page.getByRole('button',{name:'Открыть лекцию и продолжить'}).isDisabled(),true);
  await page.keyboard.press('Escape');
  await page.goto(siteUrl+'?mode=print&scope=01-project-decisions');
  await page.locator('.slide-frame').first().waitFor();
  assert.equal(await page.locator('.guided-tour').count(),0);
  assert.deepEqual(errors,[]);
  console.log('Tour passed: catalog → lecture → presenter, real audience window, completion, restart, Escape, mobile layout, empty search, print exclusion.');
} finally {await browser.close();}
