import fs from 'node:fs';
import crypto from 'node:crypto';
import cases from '../authoring/worked-cases.mjs';
const original=JSON.parse(fs.readFileSync('authoring/original-course.json','utf8'));
const version='pisid3-2026.09-template02-v1';
const c={schemaVersion:1,contentVersion:version,id:'pisid3',code:'МДК.05.01',discipline:original.title,year:'2026–2027',heroTitle:'От требований склада',heroAccent:'к модели и интерфейсу',slogan:'3 курс · Проектируем WMS: решения, данные, взаимодействие.',mascot:'brand/rhino-wms.png',mascotAlt:'Носорог и проектирование складской системы',logo:'brand/brand-mark.png',ornament:'brand/side-ornament.webp',font:'fonts/raleway-cyrillic.woff2',topicArrow:'brand/topic-arrow.webp',materialsUrl:original.materialsUrl,demo:false,semesters:[5,6],assessment:{mode:'autonomous',url:'assessment.json'},literature:{primary:[],additional:[]},glossary:[],curriculum:[],lectures:[]};
let group='';for(const line of fs.readFileSync('SOURCES.md','utf8').split('\n')){if(line.startsWith('## Основная'))group='primary';else if(line.startsWith('## Дополнительная'))group='additional';else if(line.startsWith('## '))group='';if(group&&line.startsWith('- ')){const url=line.match(/\]\((https[^)]+)\)/)?.[1];c.literature[group].push({citation:line.slice(2).replaceAll('*','').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace('ISBN 978-5-93026-166-10','ISBN требует уточнения').trim(),...(url?{url}:{})});}}
const bank={schemaVersion:1,courseId:c.id,contentVersion:version,mode:'autonomous-educational',notice:'Ключи учебной автономной самопроверки доступны технически.',keys:{}};
const teacher={schemaVersion:1,courseId:c.id,contentVersion:version,notes:{}};
const source={courseId:c.id,contentVersion:version,slides:{}};
const prior=fs.existsSync('private/teacher-source.json')?JSON.parse(fs.readFileSync('private/teacher-source.json','utf8')):null;
const withTeacher=process.argv.includes('--teacher'),questions=[],registry=[];
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const explanationOf=x=>x.definition.replace(/^[^—]+—\s*(это\s+)?/,'').replace(/\.$/,'');
const examUrl='https://disk.yandex.ru/d/Pn1NcJ-UexwpjQ';
const examContext=n=>n<=3?'КИМ 09.02.07-5-2027, задание 1: анализ документов производственного предприятия и ER-диаграмма в PDF. WMS здесь — отдельный учебный кейс; часы и темы курса не выводятся из 20 минут экзаменационного задания.':n>=10&&n<=15?'КИМ 2027, задание 1 требует 3НФ, ссылочную целостность, осмысленное именование, первичные и внешние ключи; типы данных на этапе ER-диаграммы необязательны. Эта лекция разбирает отдельную часть подготовки модели.':n>=25?'В ТЗ задания 4 КИМ 2027 заданы роли администратора и пользователя, CAPTCHA-пазл и блокировка после трёх подряд неудач пароля или пазла. Условия экзамена реализуют по ТЗ; альтернативы WMS в этой лекции не отменяют их.':null;
for(const [li,t] of original.topics.entries()){
 const l={id:t.id,title:t.title,sourceTitle:t.section,semester:t.semester,question:t.shortTitle,slides:[]};
 const add=(suffix,slide,comment={})=>{
  const s={id:t.id+'-'+suffix,kicker:'ПиДИС · 3 курс',...slide};l.slides.push(s);
  if(withTeacher){
   let note=comment.note||{script:comment.script,preparation:comment.preparation||'Учебный пример WMS; значения условные. '+t.caseContext,notebook:s.notebook||'Отдельная запись не требуется.',questions:comment.questions||'',answer:comment.answer||'',estimatedSeconds:comment.seconds||75};
   if(!note.script)throw Error('Не написана заметка '+s.id);
   if(prior?.slides[s.id]){if(prior.slides[s.id].contentHash!==digest(s))throw Error('Согласуйте заметку изменённого слайда: '+s.id);note=prior.slides[s.id].note;}
   teacher.notes[s.id]=note;source.slides[s.id]={contentHash:digest(s),note};
  }
  return s.id;
 };
 add('start',{kind:'title',title:t.shortTitle,kicker:`Лекция ${t.number} · 3 курс`,body:t.description},{script:`Сегодня разбираем тему «${t.title}». Наша цель — ${t.objective}. ${t.caseContext} В конце получим ${t.deliverable}. Пройдём четыре вопроса от смысла понятий к проверяемому решению. В каждом вопросе сопоставим корректное действие с ошибкой, разберём конкретные данные и выполним четыре задания. Важен не выбор знакомого слова, а объяснение результата и границы применимости.`,seconds:40});
 for(const g of ['primary','additional'])add(g==='primary'?'main-literature':'additional-literature',{kind:'literature',title:g==='primary'?'Основная литература':'Дополнительная литература',readingGroup:g,kicker:'Источники'},{script:`Для темы «${t.shortTitle}» используем ${g==='primary'?'основные':'дополнительные'} издания исходного курса. Они дают контекст проектирования ИС; точные страницы РПД не предоставлены. ${t.description} Примеры WMS являются авторскими и не выдаются за цитаты из книги. В конце лекции доступны предметные источники. При спорном утверждении следует проверить конкретное положение, а не только наличие ссылки в библиографии. ISBN одного унаследованного описания помечен как требующий уточнения.`,seconds:30});
 add('materials',{kind:'materials',title:'Материалы к занятиям',kicker:'Папка третьего курса'},{script:`Материалы темы «${t.shortTitle}» доступны в папке третьего курса по ссылке и QR-коду. Адрес сохранён из исходного проекта. ${t.deliverable} — ожидаемый результат самостоятельного применения. Все сведения, необходимые для обязательной самопроверки, показаны на слайдах; внешний файл не является скрытым условием ответа. Офлайн-подготовка сайта не скачивает содержимое Яндекс Диска. Для продолжения занятия достаточно самой лекции и конспекта.`,seconds:20});
 add('route',{kind:'agenda',title:'Вопросы темы',kicker:'Маршрут занятия'},{script:`Маршрут темы «${t.shortTitle}» состоит из четырёх связанных вопросов: ${[0,1,2,3].map(q=>t.concepts[q*2].name+' и '+t.concepts[q*2+1].name).join('; ')}. Для каждого вопроса сначала уточним значения, затем сравним ошибку и действие, выполним законченный пример и самопроверку. ${t.objective} — ориентир всего маршрута. Оглавление строится из реальных разделителей: оно должно оставаться согласованным при изменении структуры.`,seconds:45});
 add('why',{kind:'theory',title:'Результат нашей работы',body:t.objective,bullets:[t.deliverable,'Обоснование решения по данным и ограничениям','Проверка результата и отрицательного случая']},{script:`Здесь результат темы «${t.shortTitle}» раскрывается как ${t.deliverable}. Для качества важны источник, смысл решения и способ проверки. ${cases[li][0][0]} Именно на таких данных нужно объяснить выбор. Документ без решения не выполняет цель, а решение без проверки остаётся утверждением автора. Вопросы на слайдах помогут перейти от описания к наблюдаемому результату; отдельно сохраним то, что зависит от ответа владельца процесса.`});
 add('case',{kind:'example',title:t.caseName,body:t.caseContext,kicker:'Сквозной кейс WMS'},{script:`Контекст темы «${t.shortTitle}»: ${t.caseContext} WMS — система управления складом; ТСД — терминал сбора данных; ERP — система планирования ресурсов предприятия. Идентификаторы, сроки и числа в примерах условны. ${cases[li][0][0]} ${cases[li][0][3]} Не переносим отдельное правило склада на любую организацию: сначала проверяем исходные условия и полномочия владельца решения.`});
 add('entry',{kind:'theory',title:'Исходные знания и границы',bullets:[original.semesterThemes[t.semester],'Факт, решение и способ проверки различаются.','Программа и часы сохранены только в пределах имеющихся исходных данных; РПД не предоставлена.']},{script:`Тема «${t.shortTitle}» относится к ${t.semester} семестру: ${original.semesterThemes[t.semester]}. Используем различие подтверждённого факта, принятого решения и его проверки. ${t.description} Если данных не хватает, фиксируем вопрос или допущение. Сохранение порядка исходных тем не означает независимой проверки РПД. Оценка времени в заметках авторская: большой материал можно разделить на встречи по границам вопросов, сохраняя порядок объяснения и проверки.`});
 const exam=examContext(t.number);if(exam)add('exam-context',{kind:'theory',title:'Связь с ДЭ 2027',body:exam,source:'КИМ 09.02.07-5-2027, с. 28–32; приложение 1'},{script:`Свяжем тему «${t.shortTitle}» с предоставленным комплектом. ${exam} На экзамене необходимо читать конкретное выданное задание и приложения. Предметная область образца — производство, а лекции используют WMS. Переносится способ анализа и проверки, а не готовые сущности, числа или макеты. Вариативная часть и вид аттестации группы не указаны.`});
 for(let qi=0;qi<4;qi++){
  const pair=t.concepts.slice(qi*2,qi*2+2),[a,b]=pair,w=cases[li][qi],prefix=`Q0${qi+1}`,start=l.slides.length,title=a.name+' и '+b.name;
  const qa=`Почему нельзя: «${a.pitfall}»?\nОтвет: ${a.check}.\nКак проверяется результат «${b.name}»?\nОтвет: ${b.check}.`;
  const context=(script,extra={})=>({script,questions:qa,...extra});
  add(prefix,{kind:'section',title,kicker:`Вопрос ${qi+1}`,body:'От значения понятий к решению и проверке'},{script:`Переходим к вопросу «${title}». ${a.definition} ${b.definition} Эти понятия раскрываются в одном рабочем контексте: ${w[0]} В конце разбора сможем объяснить результат: ${w[2]} Проверим также границу: ${w[3]} Сначала разберём каждое понятие отдельно, затем соберём решение целиком.`,seconds:30});
  for(const [j,x] of pair.entries()){
   const n=qi*2+j+1,base=`c${n}`;
   const detail=`${x.definition} ${x.principle} В WMS это проявляется так: ${x.example} Корректное действие: ${x.decision} Критерий: ${x.check}.`;
   const definition=add(base+'-definition',{kind:'theory',title:x.name,kicker:'Понятие',body:x.definition,bullets:[x.principle]},context(`Уточним значение понятия «${x.name}» в теме «${t.shortTitle}». ${detail} Не смешиваем определение с названием поля или конкретной технологией. В нашем разборе ${w[0]} ${w[3]} Дальше проверим это различие на примере.`));
   add(base+'-case',{kind:'example',title:x.name+': применение',kicker:'Учебная ситуация',body:x.example,bullets:[x.decision]},context(`Рассмотрим применение «${x.name}». ${x.example} ${x.decision} ${x.check}. Значение понятия: ${explanationOf(x)}. Важна связь наблюдаемого условия и действия. ${w[0]} ${w[1]} ${w[3]} Поэтому решение проверяем на данных, а не принимаем по знакомому названию.`));
   add(base+'-decision',{kind:'comparison',title:'Ошибка и обоснованное действие',kicker:x.name,visual:{type:'comparison',columns:['Ошибка','Действие'],rows:[[x.pitfall,x.decision]],caption:'Критерий: '+x.check}},context(`Сравним два способа применить понятие «${x.name}». Ошибочный ход: ${x.pitfall}. Он не обеспечивает критерий: ${x.check}. Правильное действие: ${x.decision} ${x.example} В учебном случае ${w[0]} Итогом должно стать следующее: ${w[2]} Эта проверка делает различие между колонками предметным, а не оценочным.`));
   add(base+'-mechanism',{kind:'process',title:'Как получить проверяемый результат',kicker:x.name,visual:{type:'process',items:[{title:'Действие',text:x.decision},{title:'Проверка',text:x.check}],caption:x.example}},context(`Пройдём механизм для понятия «${x.name}». ${x.definition} Сначала выполняется действие: ${x.decision} Затем проверяется результат: ${x.check}. Не меняем порядок: критерий согласуется до того, как красивое оформление создаст впечатление готовности. ${x.example} В нашем общем случае ${w[1]} ${w[3]} При изменении исходных условий проверку повторяют.`,{seconds:95}));
   add(base+'-mistake',{kind:'warning',title:'Граница и типичная ошибка',kicker:x.name,body:x.pitfall,visual:{type:'cause',cause:x.pitfall,effect:'Не обеспечен критерий: '+x.check,solution:x.decision,caption:w[3]}},context(`Обсудим ошибку при работе с понятием «${x.name}»: ${x.pitfall}. Она существенна потому, что критерий ${x.check} перестаёт быть обеспечен. ${x.example} Исправление: ${x.decision} Дополнительная граница нашего примера: ${w[3]} Попросите объяснить, какой факт или результат нужно проверить после исправления; сравните ответ с указанным критерием.`,{seconds:95}));
   add(base+'-notebook',{kind:'notebook',title:'Запишите: '+x.name,kicker:'Конспект',notebook:x.definition+' Проверка: '+x.check},context(`Запишем смысл понятия «${x.name}» вместе с проверкой. ${x.definition} Критерий: ${x.check}. Это не перечень красивых слов, а опора для собственного решения. ${x.example} Если требуется сократить запись, сохраняем смысл и проверяемый признак. ${w[3]} По записи должно быть возможно восстановить, почему ${x.decision.toLowerCase()} Затем используем конспект при самостоятельном объяснении.`,{seconds:95}));
   c.glossary.push({term:x.name,definition:x.definition,slideIds:[definition]});
  }
  add(prefix+'-connection',{kind:'theory',title:'Связываем понятия вопроса',kicker:title,bullets:[a.name+': '+a.check,b.name+': '+b.check],body:w[2]},context(`Связь вопроса «${title}» проверяется двумя критериями. Для первого: ${a.check}; для второго: ${b.check}. ${w[0]} ${w[1]} ${w[2]} ${w[3]} Объясните, какой из критериев подтверждает результат, а какой помогает обнаружить границу. Названия понятий сохраняют разный смысл: ${explanationOf(a)}; ${explanationOf(b)}.`));
  add(prefix+'-worked',{kind:'example',title:'Полный разбор решения',kicker:'Учебные данные',body:w[0],visual:{type:'process',items:[{title:'Исходные данные',text:w[0]},{title:'Решение',text:w[1]},{title:'Результат',text:w[2]},{title:'Граница проверки',text:w[3]}],caption:'Учебный пример; значения и идентификаторы условные.'}},context(`Разберём вопрос «${title}» целиком. ${w[0]} ${w[1]} Получаем: ${w[2]} Проверяем границу: ${w[3]} В этом рассуждении ${a.name.toLowerCase()} и ${b.name.toLowerCase()} выполняют разные функции. ${a.check}. ${b.check}. После самостоятельной попытки сравните не только итог, но и основание каждого шага. Не добавляйте не подтверждённое исходными данными правило.`,{seconds:130,answer:w[2]+' '+w[3]}));
  const evidence=l.slides.slice(start).filter(s=>s.kind!=='section').map(s=>s.id),taskIds=[];
  const make=(tn,type,prompt,options,extra,key)=>{const id=`L${String(li+1).padStart(3,'0')}-${prefix}-T0${tn}`,task={id,type,prompt,...(options?{options}:{}),...extra};bank.keys[id]=key;taskIds.push(id);add(prefix+'-T0'+tn,{kind:'test',title:['Один ответ','Несколько ответов','Краткий ответ','Соответствие'][tn-1],kicker:`Самопроверка · ${tn}/4`,task},context(`Проверяем вопрос «${title}». ${prompt} Дайте время сформулировать ответ до раскрытия. ${key.explanation} Основание ответа уже было показано в определении и разборе: ${w[2]} Если возникла ошибка, вернитесь к различию понятий и критерию, а не запоминайте позицию варианта. ${w[3]}`,{answer:JSON.stringify(key,null,2),seconds:[65,85,60,100][tn-1]}));};
  const rotate=(arr,n)=>[...arr.slice(n),...arr.slice(0,n)];
  make(1,'single',`Какое действие соответствует понятию «${a.name}» в рассмотренном контексте? Выберите один ответ.`,rotate([a.decision,a.pitfall,...a.distractors].map((text,i)=>({id:'s'+i,text})),(li+qi)%4),{}, {type:'single',correct:['s0'],explanation:`${a.decision} Критерий: ${a.check}. Остальные варианты воспроизводят ошибку или нарушают назначение понятия.`,optionExplanations:{s0:a.check,s1:'Ошибка: '+a.pitfall,s2:'Не обеспечивает: '+a.check,s3:'Не обеспечивает: '+a.check}});
  make(2,'multiple','Выберите ровно два корректных действия из разбора вопроса.',rotate([a.decision,b.decision,a.pitfall,b.pitfall,b.distractors[0]].map((text,i)=>({id:'m'+i,text})),(li+qi)%5),{choose:2},{type:'multiple',correct:['m0','m1'],explanation:`Корректны оба действия: ${a.decision} ${b.decision} Их критерии: ${a.check}; ${b.check}.`,optionExplanations:{m0:a.check,m1:b.check,m2:'Ошибка: '+a.pitfall,m3:'Ошибка: '+b.pitfall,m4:'Не обеспечивает: '+b.check}});
  make(3,'short',`Назовите понятие: «${explanationOf(b)}». Используйте точное название со слайдов; регистр не важен.`,null,{}, {type:'short',accepted:[b.name],explanation:`Ответ: ${b.name}. ${b.definition} Это название понятия, а не пример его применения.`});
  const meanings=[explanationOf(a),explanationOf(b),a.pitfall,b.pitfall];
  make(4,'matching','Сопоставьте понятия и ошибки с характеристиками. Каждая используется один раз.',[2,0,3,1].map(i=>({id:'r'+i,text:meanings[i]})),{items:[a.name,b.name,'Ошибка: '+a.name,'Ошибка: '+b.name].map((text,i)=>({id:'i'+i,text}))},{type:'matching',pairs:{i0:'r0',i1:'r1',i2:'r2',i3:'r3'},explanation:`${a.definition} ${b.definition} Для первого понятия ошибка: ${a.pitfall}; для второго: ${b.pitfall}.`});
  questions.push({lectureId:l.id,questionId:`L${li+1}-${prefix}`,title,sourceConcepts:pair.map(x=>x.name),slideIds:l.slides.slice(start).map(s=>s.id),taskIds,evidence,outcome:w[2],source:'authoring/original-course.json; authoring/worked-cases.mjs',officialHours:null});
  c.curriculum.push({topic:title,outcome:w[2],source:'Авторская группировка исходных тем; РПД не предоставлена.',slideIds:evidence,taskIds});
 }
 add('summary',{kind:'summary',title:'Связи и выводы темы',bullets:cases[li].map(w=>w[2])},{script:`Подведём итог темы «${t.shortTitle}». ${cases[li].map(w=>w[2]).join(' ')} Эти результаты помогают получить ${t.deliverable}. Различайте исходные факты и принятые решения; условия примеров не являются универсальными правилами. Для собственного проекта проверьте источники и владельцев спорных условий. Вопросы по границам результата: ${cases[li].map(w=>w[3]).join(' ')}`});
 add('sources',{kind:'literature',title:'Предметные источники',references:t.sources.map(s=>({citation:s.label,url:s.url})).slice(0,3).concat(exam?[{citation:'КИМ 09.02.07-5-2027 · комплект преподавателя',url:examUrl}]:[])},{script:`Для углубления темы «${t.shortTitle}» используйте предметные источники. ${t.description} Наличие ссылки не доказывает актуальность нормативного документа: статус и область применения сверяют отдельно. Примеры и числа WMS авторские; они демонстрируют ход решения. Комплект ДЭ 2027 предоставлен преподавателем и используется только для отмеченных связей с экзаменом. РПД и официальные часы не восстановлены по предположению. Ограничения проверки источников перечислены в документации проекта.`,seconds:35});
 add('final',{kind:'summary',title:'Перенос в свой проект',bullets:['Подготовьте: '+t.deliverable,'Укажите исходные факты и допущения.','Покажите успешный и отрицательный случай.','Откройте итоговый файл и проверьте согласованность.']},{script:`Самостоятельный результат темы «${t.shortTitle}» — ${t.deliverable}. Переносим способ анализа и проверки на ваши данные. ${cases[li][3][0]} ${cases[li][3][1]} ${cases[li][3][2]} ${cases[li][3][3]} В собственном проекте сначала замените учебные предположения подтверждёнными условиями, затем проверьте критерии каждого решения. Файл должен позволять другому участнику понять основание результата без устного пересказа всей лекции.`});
 add('questions',{kind:'questions',title:'Вопросы от аудитории',bullets:['Какое исходное условие меняет решение?','Где нужна дополнительная проверка?','Как показать результат другому участнику проекта?']},{script:`Завершим тему «${t.shortTitle}» обсуждением. ${cases[li].map(w=>w[3]).join(' ')} Вернитесь к любому примеру и назовите факт, действие и проверяемый результат. Если вопрос выходит за подтверждённые условия, фиксируем его вместе с предполагаемым источником ответа. Ключевой итог занятия: ${t.objective}. Сохраняем конспект и список уточнений для следующей темы.`});
 c.lectures.push(l);registry.push({lectureId:l.id,title:l.title,semester:l.semester,hours:null,slides:l.slides.length,questions:4,tasks:16,visuals:l.slides.filter(s=>s.visual).length,contentVersion:version,estimatedMinutes:withTeacher?Math.round(l.slides.reduce((n,s)=>n+teacher.notes[s.id].estimatedSeconds,0)/60):null});
}
const glossary=new Map();for(const g of c.glossary){const key=g.term+'|'+g.definition;if(glossary.has(key))glossary.get(key).slideIds.push(...g.slideIds);else glossary.set(key,g);}c.glossary=[...glossary.values()];
for(const d of ['public','reports','private','private/lectures'])fs.mkdirSync(d,{recursive:true});
const write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');
write('public/course.json',c);write('public/assessment.json',bank);write('authoring/questions.json',questions);write('reports/registry.json',registry);
if(withTeacher){write('private/teacher-pack.json',teacher);write('private/teacher-source.json',source);for(const l of c.lectures){const notes=Object.fromEntries(l.slides.map(s=>[s.id,teacher.notes[s.id]]));write('private/lectures/'+l.id+'.json',{...teacher,notes});fs.writeFileSync('private/lectures/'+l.id+'.md','# '+l.title+'\n\n'+l.slides.map(s=>{const n=notes[s.id];return `## ${s.id} · ${s.title}\n\n${n.script}\n\nПодготовка: ${n.preparation}\n\nКонспект: ${n.notebook}\n\n${n.questions}\n\n${n.answer}\n\nОценка: ${n.estimatedSeconds} с.\n`;}).join('\n'));}write('private/preparation-cards.json',c.lectures.map((l,i)=>({lectureId:l.id,logic:questions.filter(q=>q.lectureId===l.id).map(q=>q.title),prerequisites:i?'Предшествующие темы курса; факт, решение, проверка.':'Понятие ИС и описание рабочей задачи.',uncertainties:['РПД и официальные часы не предоставлены.','Учебные данные WMS условны.'],estimatedMinutes:registry[i].estimatedMinutes})));}
console.log(JSON.stringify({lectures:c.lectures.length,slides:c.lectures.reduce((n,l)=>n+l.slides.length,0),tasks:Object.keys(bank.keys).length,notes:Object.keys(teacher.notes).length}));
